AdRoll/rebar3_format

- test_app/after/src/hrl.erl
- test_app/after/src/test_sup.erl
- test_app/after/src/unicode_support.erl
- test_app/src/hrl.erl
- test_app/src/r3fmt_test_app.app.src
- test_app/src/test_sup.erl
- test_app/src/unicode_support.erl
Fixes #13.
* Application name and app module name clash (both were `app_test`). Changed app name to `r3fmt_test_app`.
*  Including `header.hrl` instead of `.erl`.
* Renamed `unicode` module to `unicode_support`.
> #13 Fix make compile target

- src/rebar3_format.erl
- src/rebar3_format_prv.erl
- src/rebar3_formatter.erl
- src/rebar3_prettypr.erl
It seems like on #1, we replaced tabs by 2 spaces, when OTP actually uses 8 spaces for tabs.
Therefore the code is awfully (mis)indented now.
So, I tried to reformat it, by applying the formatter.
While I was at, I thought of also applying it to the rest of the code (just for kicks) and the result was not disappointing.
The only thing I needed to change afterward was the tabs. I manually replaced them by 8 spaces and that was it.
So, I fixed #2… kinda… We still need to incorporate the formatter on our pre-commit hooks or as part of `make test`… I'll open another ticket for that.
> Fixes 2: Apply the formatter to its own code

- src/rebar3_prettypr.erl
- test_app/after/src/erl_tidy_tilde.erl
- test_app/after/src/igor_type_specs.erl
- test_app/after/src/m1.erl
- test_app/after/src/m2.erl
- test_app/after/src/macros.erl
- test_app/after/src/others.erl
- test_app/after/src/specs_and_funs.erl
- test_app/after/src/syntax_tools_SUITE_test_module.erl
- test_app/after/src/syntax_tools_test.erl
- test_app/after/src/type_specs.erl
- test_app/rebar.config
- test_app/src/erl_tidy_tilde.erl
- test_app/src/igor_type_specs.erl
- test_app/src/m1.erl
- test_app/src/m2.erl
- test_app/src/macros.erl
- test_app/src/others.erl
- test_app/src/specs_and_funs.erl
- test_app/src/syntax_tools_SUITE_test_module.erl
- test_app/src/syntax_tools_test.erl
- test_app/src/type_specs.erl
In this PR I had…
* copied the tests from OTP's `syntax_tools` app.
* removed some unused code from `rebar3_prettypr`.
* added enough weird examples to cover most if not all of the module's code paths.
I reached 91% coverage… the remaining 9% is full of irreproducible edge-cases and catch-all clauses that are never evaluated _in our world_.
> Fix 21: Complete coverage on rebar3_prettypr

- rebar.config
Right now rebar3_lint uses an older version of the katana-code library.
> Recover the linting as a plugin, once rebar3_lint uses katana_code 0.2.1

- README.md
- src/rebar3_formatter.erl
- src/rebar3_prettypr.erl
- test_app/after/src/inline_items.erl
- test_app/src/inline_items.erl
I also improved `rebar3_prettypr`'s code a bit.
Feel free to look at `inline_items.erl` and tell me which things should not be considered _lists_ for the purposes of `inline_items`. I just made it affect everything that was possibly concatenated with `,` or `|`.
> Fix #32: don't put more one item per row

- README.md
- src/rebar3_formatter.erl
- src/rebar3_prettypr.erl
- test_app/after/src/newline_after_attributes.erl
- test_app/src/newline_after_attributes.erl
Not the whole thing, but at least we can now avoid the dreaded empty lines after exports, types and specs.
> [#30] Add an option to avoid adding empty lines after attributes

- src/rebar3_format_prv.erl
Some times it is hard to find the error in a file. Having the line number would be really neat and helps debugging a lot.
> Show line number of unparsable file

- src/default_formatter.erl
- test_app/after/src/dodge_macros.erl
- test_app/after/src/type_specs.erl
- test_app/src/dodge_macros.erl
Fix #58: Properly dodge and undodge macros on specs and types
> Fix #58: Properly dodge and undodge macros on specs and types

- README.md
- src/default_formatter.erl
- src/otp_formatter.erl
- test_app/after/src/inline_attributes.erl
- test_app/after/src/inline_items.erl
- test_app/after/src/not_inline_attributes.erl
- test_app/after/src/syntax_tools_SUITE_test_module.erl
- test_app/src/inline_attributes.erl
- test_app/src/not_inline_attributes.erl
Fixes #88 by adding `inline_attributes` with default `all`.
> [Fix #88] Add inline_attributes as a separate flag to inline_items

- README.md
- src/formatters/erlfmt_formatter.erl
- test/erlfmt.app
- test/erlfmt.erl
- test/erlfmt_formatter_SUITE.erl
Part of #110. Just like #112, but for WhatsApp's `erlfmt`.
> [#110] Allow users to use erlfmt from within rebar3 format

- README.md
I added support for `rebar3_format` to my VS Code extension. It's working pretty well so far, at least for me!
> Add link to VS Code extension

- src/formatters/default_formatter.erl
- test_app/after/src/strings.erl
- test_app/src/strings.erl
We still can't handle multi-block strings, so the "implicit" concatenation thing will still happen, but at least now `\x61` will not be turned into `a`.
> [#55] Some initial steps

- README.md
- src/formatters/default_formatter.erl
- test_app/after/src/quoted_atoms.erl
- test_app/after/src/unquoted_atoms.erl
- test_app/src/quoted_atoms.erl
- test_app/src/unquoted_atoms.erl
Add new option (`unquote_atoms`) with default `true`, to preserve atom quoting.
> [Fix #56] Handle quoted atoms

- src/formatters/default_formatter.erl
- src/formatters/erlfmt_formatter.erl
- src/formatters/otp_formatter.erl
- src/formatters/sr_formatter.erl
- src/rebar3_ast_formatter.erl
- src/rebar3_format_prv.erl
- test/erlfmt.erl
- test_app/after/src/indent_18.erl
- test_app/after/src/indent_81.erl
- test_app/after/src/inline_clause_bodies.erl
- test_app/after/src/inline_items.erl
- test_app/after/src/syntax_tools_SUITE_test_module.erl
Fixes #90 by indenting long specs on `->`. The alternative of turning them into constrained specs (i.e. with `when`) was impossible to get right since the formatter would've had to come up with "sensible" variable names for the types.
> [Fix #90] Indent specs on ->

- src/formatters/default_formatter.erl
- src/formatters/erlfmt_formatter.erl
- src/formatters/otp_formatter.erl
- src/formatters/sr_formatter.erl
- src/rebar3_ast_formatter.erl
- src/rebar3_format_prv.erl
- src/rebar3_formatter.erl
- test/erlfmt.erl
- test/erlfmt_formatter_SUITE.erl
- test/steamroller.erl
- test_app/after/src/brackets.erl
- test_app/after/src/indent_18.erl
- test_app/after/src/indent_81.erl
- test_app/after/src/inline_items.erl
- test_app/after/src/others.erl
- test_app/after/src/weird.erl
Fixes #75 by indenting long matching expressions on `=`.
> [Fix #75] Indent long lines on =

- .travis.yml
- src/formatters/otp_formatter.erl
- test/test_app_SUITE.erl
- test_app/after/src/otp23.erl
- test_app/src/otp23.erl
- Apply https://github.com/erlang/otp/commit/d1c8f8c811662e7e6209c57abec651209459a701 and other newer commits to `otp_formatter`.
- Add tests for OTP23-style features.
[Fix #105]
> [Fix #105] Adjust to OTP23

- README.md
- src/formatters/default_formatter.erl
- src/formatters/erlfmt_formatter.erl
- src/formatters/otp_formatter.erl
- src/formatters/sr_formatter.erl
- src/rebar3_ast_formatter.erl
- src/rebar3_format_prv.erl
- src/rebar3_formatter.erl
- test/test_app_SUITE.erl
- test_app/after/src/break.erl
- test_app/after/src/catch_test.erl
- test_app/after/src/igor_type_specs.erl
- test_app/after/src/indent_1.erl
- test_app/after/src/indent_8.erl
- test_app/after/src/inline_clause_bodies.erl
- test_app/after/src/inline_items.erl
- test_app/after/src/others.erl
- test_app/after/src/receive_after.erl
- test_app/after/src/syntax_tools_SUITE_test_module.erl
- test_app/after/src/syntax_tools_test.erl
- test_app/after/src/type_specs.erl
- test_app/after/src/weird.erl
- test_app/src/indent_1.erl
- test_app/src/indent_8.erl
To fix #131, I just removed `sub_indent`. I didn't change `break_indent`'s name to just `indent` since it's still different from other _indentation_ rules, like the one for indenting items in a list, where the elements are indented by `1` only, e.g.:
```erlang
[first,
second,
third]
```
> Remove sub_indent altogether from the default_formatter

- rebar.lock
- src/formatters/default_formatter.erl
- src/formatters/erlfmt_formatter.erl
- src/formatters/otp_formatter.erl
- src/formatters/sr_formatter.erl
- src/rebar3_ast_formatter.erl
- src/rebar3_formatter.erl
- test/erlfmt_formatter_SUITE.erl
- test/sr_formatter_SUITE.erl
- test/test_app_SUITE.erl
- test_app/after/src/function_composition.erl
- test_app/after/src/indent_1.erl
- test_app/after/src/indent_8.erl
- test_app/src/function_composition.erl
This PR "fixes #140". It's very _hacky_ and it may lead to unexpected scenarios.
The idea behind it can be seen in `function_composition.erl`, but in a nutshell:
* The new behaviour only applies to function compositions; e.g. `f(g(h(…)))`
* The new behaviour only applies when function composition happens in the first argument of a function; e.g. not in this case: `f(a,g(b,h(c)))`.
* The new behaviour only applies when the functions that are composed are fully qualified (being that a _proxy_ for _has a long name_); e.g. in this case `d(f:f(g:g(h(…))))` the formatter will always put `g:g(…)` in the next row, but not `h(…)` nor `f:f(…)` will be moved to a new row.
This is far from ideal, but the way to properly indent things only when they're _in fact_ too long (i.e. using `sep/1` or …
> [Fix #140] Indent on function composition

- src/formatters/default_formatter.erl
- test/test_app_SUITE.erl
- test_app/after/src/indent_1.erl
- test_app/after/src/indent_8.erl
- test_app/after/src/others.erl
- test_app/src/others.erl
[Fix #163] Indent `case…of` like `try…of` if the expression spans multiple lines.
> [Fix #163] Indent case…of like try…of

- README.md
- src/formatters/default_formatter.erl
- test/test_app_SUITE.erl
- test_app/after/src/function_composition_inline.erl
- test_app/src/function_composition_inline.erl
Create a new setting for the changes done in #140 / #153 since they're not _for everyone_.
> Put #140 / #153 behind a flag

- src/formatters/default_formatter.erl
- src/formatters/otp_formatter.erl
- src/rebar3_format_prv.erl
- test_app/after/src/funs.erl
- test_app/after/src/inline_items.erl
- test_app/after/src/no_inline_funs.erl
[Fix #168] Avoid indenting match expressions if it's just a short var.
I don't think this is worth a config setting, but let me know if you want something like…
```erlang
inline_match_expressions => all | short_vars | none
```
> [Fix #168] Avoid indeting match expressions if it's just a short var

- src/formatters/erlfmt_formatter.erl
- test/erlfmt.erl
- test/erlfmt_formatter_SUITE.erl
- test_app/after/src/minimal.erl
- test_app/src/minimal.erl
[Fix #149] Add support for erlfmt `0.7.0` and drop support for `0.6.0` since the API differs way too much.
/cc @michalmuskala @awalterschulze
> [Fix #149] Add support for erlfmt 0.7.0

- src/rebar3_format_prv.erl
[Fix #145] Report the results of --verify in a non-erlang-ish way…
```bash
===> The following files are not properly formatted:
src/weird.erl
src/unquoted_atoms.erl
src/syntax_tools_test.erl
```
> [Fix #145] Report the results of --verify in a non-erlang-ish way

- README.md
- src/formatters/erlfmt_formatter.erl
- test/erlfmt_formatter_SUITE.erl
Fix #180: Add support for `erlfmt` `0.8.0`, without losing support for `0.7.0` just yet.
/cc @michalmuskala @awalterschulze
> Fix #180: erlfmt 0.8.0

- src/rebar3_format_prv.erl
I added a way to pass multiple files/wildcards to rebar3_format.  We can try it running something like this:
```
$ rebar3 format --files src/file1.erl --files src/file2.erl
```
Note that we have to write `--files` for each different file/wildcard because [getopt](https://github.com/jcomellas/getopt#argument-types) doesn't handle list arguments.
To test it i created a `_checkouts` directory inside `test_app/` and cloned my branch there.
Then I ran
```
$ rebar3 deps
$ rebar3 format --files src/break.erl --files src/catch_test.erl
```
> [fix #144] handle more than 1 wildcard

- README.md
- src/formatters/default_formatter.erl
- test_app/after/src/function_composition.erl
- test_app/after/src/function_composition_inline.erl
- test_app/after/src/function_composition_spaces.erl
- test_app/after/src/spaces_around_fields.erl
- test_app/src/function_composition.erl
- test_app/src/function_composition_inline.erl
- test_app/src/function_composition_spaces.erl
- test_app/src/spaces_around_fields.erl
[Fix #148] Add options to space out parentheses and curly braces.
I'm actually, personally, a huge fan of…
```erlang
-format #{
spaces_around_fields => true,
spaces_around_arguments => true,
inline_qualified_function_composition => true
}.
```
I think that having some extra spaces in things like `a( function:call( #{ with => parameters } ) )` is a price I'm willing to pay in order to have a consistent indentation of function calls and field lists.
Stuff like…
```erlang
this() ->
#{
is => exactly,
how =>
i:would(
write,
my,
code
)
}.
```
I kept `false` as the default in those fields, tho… mostly to avoid _controversies_ around `stuff:like( this ) or this( )`.
> [Fix #148] Add options to space out parentheses and curly braces

- src/rebar3_ast_formatter.erl
- test_app/after/src/macros.erl
- test_app/src/macros.erl
The code ends up extremely ugly since it's "formatted" directly by `ktn_dodge`, but at least it's semantically correct.
> Don't crash on weird macros

- src/formatters/default_formatter.erl
- test_app/after/src/dialyzer.erl
- test_app/src/dialyzer.erl
Fixes #210 since `inline` is not an attribute on its own, it's a parameter for `compile`.
> [Fix #210] Actually use arity qualifiers for inlining directives.

- src/formatters/default_formatter.erl
- src/formatters/otp_formatter.erl
- test_app/after/src/indent_18.erl
- test_app/after/src/indent_81.erl
- test_app/after/src/inline_items.erl
- test_app/after/src/operator_indentation.erl
- test_app/after/src/operator_indentation_with_parens.erl
- test_app/after/src/others.erl
- test_app/after/src/parentheses_yes.erl
- test_app/src/operator_indentation.erl
- test_app/src/operator_indentation_with_parens.erl
> [Fix #185] Place infix operators in columns
Let me know if you want to put this new formatting behavior behind a configuration option, although I think it will be more maintainable to keep it as the default.
> [Fix #185] Place infix operators in columns

- src/formatters/default_formatter.erl
- test_app/after/src/operator_indentation.erl
- test_app/after/src/operator_indentation_with_parens.erl
Fix #219 but, instead of not indenting _some_ operators… just don't indent after _any_ operator.
The code is more maintainable and the results will be consistent. I think this is better than what the ticket asks for.
> [Fix #219] Don't indent right after an operator

- rebar.config
- src/formatters/default_formatter.erl
Applying `hank` to this project…
First we've got this warning…
```erlang
src/formatters/default_formatter.erl:58: Field user in record ctxt is unused
```
Then, after removing that field…
```erlang
src/formatters/default_formatter.erl:38: ?NOUSER is unused
```
Niiice! ☺️
> Kill dead code with fire 🔥

- src/formatters/default_formatter.erl
- src/rebar3_ast_formatter.erl
- test_app/after/src/inline_clause_bodies.erl
- test_app/after/src/no_inline_funs.erl
- test_app/src/inline_clause_bodies.erl
- test_app/src/no_inline_funs.erl
[Fix #223] Don't let inline_simple_funs affect inline_clause_bodies
> [Fix #223] Don't let inline_simple_funs affect inline_clause_bodies

- src/formatters/default_formatter.erl
- test_app/after/src/attrs.erl
- test_app/src/attrs.erl
Fix #227: Don't put parentheses around `ignore`.
> Fix #227: Don't put parentheses around 'ignore'

- test/test_app_SUITE.erl
- test_app/after/rebar.config
Related to issue https://github.com/AdRoll/rebar3_format/issues/251.
The main logic for default formatting was added in the scope https://github.com/AdRoll/rebar3_format/pull/230. The latest version of plugin do formatting as well for `*.config` files in the root folder by default. But at the same time was miss in test cases.
> Add rebar.config for tests

- elvis.config
- src/formatters/default_formatter.erl
- src/formatters/otp_formatter.erl
- src/rebar3_format_prv.erl
Thanks to @erlang-ls, I found that we were using Elvis incorrectly in this project
> Improve Elvis usage

- README.md
- src/rebar3_format_prv.erl
- test/erlfmt_formatter_SUITE.erl
- test/otp_formatter_SUITE.erl
- test/sr_formatter_SUITE.erl
- test/test_app_SUITE.erl
Default wildcards are now applied to all app directories,
and special care is taken so that behaviour is the same if the app
directory is the root directory.
Unfortunately, had to modify quite a lot of tests - first, to invoke app
discovery (as specified by the provider); second, test_app test changed
the working directory without re-updating the state, and that obviously
didn't work out great.
------
Let me know if you'd like some touch-ups - my priorities were "make it work" and "adjust the tests so that there are no false negatives". This definitely resulted in some less-than-ideal code.
> Added app discovery to rebar3 format provider.

- src/formatters/default_formatter.erl
- test_app/after/src/strings/strings.erl
- test_app/src/strings/strings.erl
Fix #280.
Actually, it's sort of a _workaround_ to preserve the semantic value of the string while still being able to trim trailing whitespace from files easily.
I think it's a good tradeoff since, just like not too many people start their multiline strings with tabs, not too many people should finish them with spaces.
> [#280] Fix #280: Handle space-terminated strings

- src/rebar3_format.erl
- test.dict
Notifying that rebar_format must be run as a plugin, not as an escript.
> Notify escript not supported
