src/rebar3_formatter.erl
test_app/after/src/unicode.erl
test_app/src/unicode.erl

This PR ensures that the formatter works ok with unicode input.

Fix 52 ensure unicode works

---

.travis.yml

Let Travis review our PRs and run our tests for them.

Add the project to TravisCI

---

README.md
src/rebar3_format_prv.erl
src/rebar3_formatter.erl
src/rebar3_prettypr.erl
test_app/after/src/indent_18.erl
test_app/after/src/indent_81.erl
test_app/src/indent_18.erl
test_app/src/indent_81.erl

This is the first step towards #7 (indentation configuration).
No tabs vs. spaces, yet… but at least we can determine how many spaces to use.

Allow configuration of indent sizes

---

rebar.config
scripts/format
src/rebar3_format_prv.erl
src/rebar3_formatter.erl
test/test_app_SUITE.erl

Format the code for rebar3_format on make test

---

README.md
src/default_formatter.erl
test_app/after/src/brackets.erl
test_app/after/src/inline_items.erl
test_app/after/src/strings.erl
test_app/src/brackets.erl
test_app/src/inline_items.erl
test_app/src/strings.erl

Fix #60: Allow for long binaries/lists to be inlined while short ones are not.

Fix #60: Perfect inline_items

---

src/rebar3_format_prv.erl

Update default wildcard to only .erl/.hrl files

---

README.md

I clarified the info no the README.md regarding what's discussed on #88, but I'm unsure if this will suffice.

[#88] Clarify description of  in README.md

---

src/rebar3_formatter.erl
test_app/after/src/test.erl
test_app/src/test.erl

Fix modified_ast issue

---

priv/scripts/format
src/formatters/default_formatter.erl
src/formatters/erlfmt_formatter.erl
src/formatters/otp_formatter.erl
src/formatters/sr_formatter.erl
src/rebar3_format_prv.erl
src/rebar3_formatter.erl

[Fix #110] Allowing what we discussed with @dtip on #112 related to formatter global initialization.

[Fix #110] Refactor rebar3_formatter behavior

---

priv/scripts/format
src/formatters/default_formatter.erl
src/formatters/erlfmt_formatter.erl
src/formatters/otp_formatter.erl
src/formatters/sr_formatter.erl
src/rebar3_format_prv.erl
src/rebar3_formatter.erl
test/steamroller.erl

Now using the new `opts/2` function added to `v0.14.3`

[Fix #117] Full steamroller integration

---

src/formatters/erlfmt_formatter.erl
test/erlfmt_formatter_SUITE.erl

Because @michalmuskala and his friends released `v0.2.0` of `erlfmt` today.

Add support for erlfmt 0.2.0

---

src/formatters/erlfmt_formatter.erl
test/erlfmt_formatter_SUITE.erl

/cc @whatsapp / @michalmuskala

Add support for new features in erlfmt v0.5.1

---

src/formatters/default_formatter.erl
src/rebar3_format_prv.erl
test/test_app_SUITE.erl
test_app/after/src/indent_18.erl
test_app/after/src/indent_81.erl
test_app/after/src/inline_items.erl
test_app/after/src/others.erl

[Fix #127] Remove extra spaces in binary comprehensions.

[Fix #127] Extra spaces in binary comprehensions

---

src/formatters/erlfmt_formatter.erl
test/erlfmt.erl
test/erlfmt_formatter_SUITE.erl

[Fix #135] Compatibilize with erlfmt 0.6.0 and 0.5.1

[Fix #135] Compatibilize with erlfmt 0.6.0 and 0.5.1

---

README.md
src/formatters/default_formatter.erl
src/formatters/otp_formatter.erl
src/rebar3_ast_formatter.erl
src/rebar3_format_prv.erl
src/rebar3_formatter.erl
test/erlfmt.erl
test/erlfmt_formatter_SUITE.erl
test/sr_formatter_SUITE.erl
test/steamroller.erl
test_app/after/src/funs.erl
test_app/after/src/inline_items.erl
test_app/after/src/no_inline_funs.erl
test_app/after/src/specs_and_funs.erl
test_app/src/funs.erl
test_app/src/no_inline_funs.erl

When I fixed #142, I forgot to reduce…
```erlang
fun() ->
x
end
```
…to…
```erlang
fun() -> x end
```
This PR solves that.

Inline simple funs even more aggressively

---

src/formatters/default_formatter.erl
test_app/after/src/dialyzer.erl
test_app/after/src/newline_after_attributes.erl
test_app/src/dialyzer.erl

[Fix #141] Format -dialyzer properly

[Fix #141] Format -dialyzer properly

---

README.md
rebar.config
test_app/rebar.config

[Fix #173] Use/recommend project_plugins, instead of plugins

[Fix #173] Use/recommend project_plugins, instead of plugins

---

README.md
src/formatters/default_formatter.erl
test_app/after/src/matches.erl
test_app/after/src/parentheses_no.erl
test_app/after/src/parentheses_yes.erl
test_app/src/matches.erl
test_app/src/parentheses_no.erl
test_app/src/parentheses_yes.erl

[Fix #139] Add an option to forcefully add parentheses around infix operators
…plus two test files I missed in #175 🙄

[Fix #139] parentheses around infix operators

---

src/formatters/default_formatter.erl
test_app/after/src/break.erl
test_app/after/src/indent_1.erl
test_app/after/src/indent_8.erl
test_app/after/src/others.erl
test_app/after/src/receive_after.erl
test_app/after/src/syntax_tools_test.erl
test_app/src/others.erl

Left some comments for discussion.

[Fix #183] Properly indent after on receive

---

src/formatters/default_formatter.erl
test_app/after/src/dialyzer.erl
test_app/src/dialyzer.erl

[Fix #201] Arity qualifiers for -inline

[#201] [Fix #201] Arity qualifiers for -inline

---

src/formatters/default_formatter.erl
test_app/after/src/records.erl
test_app/src/records.erl

[Fix #198] Allow A#record.with_another#record.in_it

[Fix #198] Allow A#record.with_another#record.in_it

---

src/formatters/default_formatter.erl
src/formatters/otp_formatter.erl
test_app/after/src/comments.erl
test_app/src/comments.erl

[Fix #200] Fix arrangment of comments at the first paramter of an application

[Fix #200] Fix arrangment of comments at the first paramter of an application

---

rebar.config
rebar.lock
src/formatters/default_formatter.erl
src/rebar3_ast_formatter.erl
test/test_app_SUITE.erl
test_app/after/src/a_script.sh
test_app/after/src/macros.erl
test_app/after/src/others.erl
test_app/after/src/syntax_tools_test.erl
test_app/src/a_script.sh

Fix #118: Parse escripts

---

README.md
src/rebar3_ast_formatter.erl
test_app/after/src/dont_parse_macros.erl
test_app/after/src/macros.erl
test_app/after/src/parse_macros.erl
test_app/after/src/syntax_tools_test.erl
test_app/src/dont_parse_macros.erl
test_app/src/macros.erl
test_app/src/parse_macros.erl
test_app/src/syntax_tools_test.erl

Fix #217: Put no-macro-parsing behind an option

[#217] Fix #217: Put no-macro-parsing behind an option

---

README.md
elvis.config
priv/scripts/format
rebar.config
rebar.lock
src/formatters/default_formatter.erl
src/rebar3_ast_formatter.erl
src/rebar3_format.app.src
src/rebar3_format_prv.erl
test/test_app_SUITE.erl
test_app/after/src/r3fmt_test_app.app.src

Fix #86: Add support for formatting files like rebar.config, elvis.config and my_app.app.src

[#86] Add support for non-module files

---

src/formatters/default_formatter.erl
test_app/after/src/macros_in_specs.erl
test_app/src/macros_in_specs.erl

[Fix #231] Handle macros in specs and types

[Fix #231] Handle macros in specs and types

---

src/formatters/default_formatter.erl
test_app/after/src/ignore.erl
test_app/src/ignore.erl

Related to https://github.com/AdRoll/rebar3_format/issues/247

Fix for #247

---

src/formatters/default_formatter.erl
test_app/after/src/records.erl
test_app/src/records.erl

Fixes #249. Small fix, but was also need to update `test_app`...

Fixes #249: Spacing for empty records

---

src/formatters/default_formatter.erl
test/test_app_SUITE.erl
test_app/after/src/binary_fields.erl
test_app/after/src/macros_in_binary.erl
test_app/src/binary_fields.erl
test_app/src/macros_in_binary.erl

Another way to fix #81, an alternative to #257.

[#81] Alternative approach to fix #81

---

priv/scripts/format

[Fix #270] Remove useless message

[Fix #270] Remove useless message

---

rebar.config

Such recursion. Much formatting.

Allow the formatter to be run on the formatter to format the formatter

---

.github/workflows/erlang.yml
elvis.config
rebar.config
src/formatters/default_formatter.erl
src/formatters/otp_formatter.erl
src/rebar3_format.app.src

Some CI -related tweaks

---

.github/workflows/erlang.yml
nextroll.dict
rebar.config
rebar.lock
src/formatters/default_formatter.erl
src/formatters/otp_formatter.erl
test/otp_formatter_SUITE.erl
test/test_app_SUITE.erl
test_app/after/src/otp25.erl
test_app/after/src/otp_samples/syntax_tools_test.erl
test_app/src/otp25.erl
test_app/src/otp_samples/syntax_tools_test.erl

Waiting on AdRoll/rebar3_hank#181 to get merged for CI to pass cleanly here.

Fix #302: Get the formatter ready for OTP25

---

README.md
nextroll.dict
src/formatters/default_formatter.erl
src/rebar3_ast_formatter.erl
test_app/after/src/sort_arity_qualifiers/sort_arity_qualifiers_checklist.erl
test_app/after/src/sort_arity_qualifiers/sort_arity_qualifiers_multiple_export_lists.erl
test_app/after/src/sort_arity_qualifiers/sort_arity_qualifiers_single_export_list.erl
test_app/after/src/sort_arity_qualifiers/sort_arity_qualifiers_uppercase_names.erl
test_app/after/src/sort_arity_qualifiers/sort_arity_qualifiers_utf_names.erl
test_app/src/sort_arity_qualifiers/sort_arity_qualifiers_checklist.erl
test_app/src/sort_arity_qualifiers/sort_arity_qualifiers_multiple_export_lists.erl
test_app/src/sort_arity_qualifiers/sort_arity_qualifiers_single_export_list.erl
test_app/src/sort_arity_qualifiers/sort_arity_qualifiers_uppercase_names.erl
test_app/src/sort_arity_qualifiers/sort_arity_qualifiers_utf_names.erl

Expand sorting of arity qualifiers to more attributes

---

rebar.config
rebar.lock

~⚠️ Don't merge yet. 😄~
The goal is to up `katana_code` in a way that this plugin can be imported without issue elsewhere.

Feature a new katana
